### ISSUE TITLE
Inverted 2-mer bases 

### ISSUE THREAD

**Issue by alimayy** [fxia22/HINGE#82]
I've noticed another difference when I used racon instead of the default consensus module. We've previously noticed that the default consensus module sometimes results in inverted 2-mers in the assembly. If you look at file1, where you see the reads aligned to the default consensus assembly, you'll realise the inverted bases. Note that TC is inverted to CT in the assembly
![file1](https://cloud.githubusercontent.com/assets/22055534/19703346/cd2694fa-9b03-11e6-8bd7-95e1c4bbaa7a.PNG)
For this particular assembly we've realised that this happened more than 20,000 times.

When I used racon instead, the issue is not there. See file2, where the top sequence is the assembly from default consensus and the bottom is the consensus with racon.
![file2](https://cloud.githubusercontent.com/assets/22055534/19703439/214769e2-9b04-11e6-8201-4f2f28d4b3e2.PNG)

Hope you find this useful.

**Comment by ilanshom** [comment]
@alimayy, that's definitely very useful, thank you.
It turned out we were calling some deletions off by one base. I just fixed that and pushed it into master. Let me know if it solves your problem.

By the way, what are these reads that you are aligning onto the consensus? They seem too clean to be pacbio reads. Are they illumina reads?

**Comment by alimayy** [comment]
Thanks @ilanshom, I'll check it today. One question though, would it be fine if I just consistently use the dev branch only? I mean, are all changes in the master also in dev?

Regarding your question, the first figure was created by a client of ours, so I'm not sure what exactly he did there. Although you're probably right, it's very likely that this was a hybrid sequencing project and that these are Illumina reads.

**Comment by ilanshom** [comment]
Sure, you can just use dev. We merged the changes there as well.

**Comment by alimayy** [comment]
@ilanshom I'll check it, but this change does not solve the GC% issue right?

**Comment by ilanshom** [comment]
I'm still trying to figure out what could have caused the GC% issue. I only made changes trying to fix the 2-mer inversion issue, and I don't expect that to affect the GC%.

**Comment by alimayy** [comment]
@ilanshom are you able to reproduce the GC% issue on your test sets? Otherwise I'm willing to share everything I have (all the commands I use, all outputs etc). Unfortunately excluding the raw reads till I hear from the client. Thing is, the draft assemblies have the right GC%, so it looks like it indeed has to do with the consensus module. I tried it both with and without norevcomp and the GC% only happens after consensus calling in both cases.

**Comment by fxia22** [comment]
@alimayy Thanks, I will handle the dependency.

It will be nice the get your draft assembly and consensus assembly produced by hinge consensus module.

**Comment by ilanshom** [comment]
Yes, having the draft assembly and consensus assembly would help. We are currently not able to reproduce the GC% issue here. 

Would you say that the skew in the GC content is mainly caused by the large number of poly A segments? We could make some changes to what the consensus module writes to the log file to try to figure out why that's happening.

**Comment by alimayy** [comment]
@fxia22 @ilanshom I still haven't heard from our client. I'll try to get permission for sharing the draft and final assemblies in the worst case if I can't share the raw reads.

If you recall, in one of the datasets I have 11% less GC compared to the reference when I use the hinge consensus module. In that assembly I have three contigs, the longest of which is 2,455,789 long (the reference genome is 2.7 MB). In this long contig I just counted 169 instances of a 2567 bp long polyA fragment, which is 433,823 As. This might be one of the reasons.

I'd be glad to help with the log file if you want to change the consensus module for reporting purposes.

**Comment by ilanshom** [comment]
Thanks @alimayy. It seems that the problem is that when the coverage on a base from a contig is 0, we were defaulting the base at that point to A (instead of using the actual base on the draft contig). I just fixed that, and I'm hoping it will fix the issue. Could you try and let me know?

**Comment by alimayy** [comment]
Congratulations 👍 👍  It is indeed resolved. 

HINGE consensus caller:
---------------------------------
```
Assembly statistics:
Number of sequences     3
Sum (bp)        2,686,191
GC contents in %        68.86
Max sequence size       2,439,297
Min sequence size       19,939
Average sequence size   895,397
N25     2,439,297
N50     2,439,297
N75     2,439,297
Number of gaps  0
Size of gaps    0
---------------------------------
Contig statistics:
Minimum scaffold length Number of scaffolds     Total scaffold length
0       3       2,686,191
500     3       2,686,191
1,000   3       2,686,191
5,000   3       2,686,191
10,000  3       2,686,191
1,000,000       1       2,439,297
---------------------------------

```

racon consensus output:
```
---------------------------------
Assembly statistics:
Number of sequences     3
Sum (bp)        2,665,777
GC contents in %        68.86
Max sequence size       2,420,613
Min sequence size       19,939
Average sequence size   888,592
N25     2,420,613
N50     2,420,613
N75     2,420,613
Number of gaps  0
Size of gaps    0
---------------------------------
Contig statistics:
Minimum scaffold length Number of scaffolds     Total scaffold length
0       3       2,665,777
500     3       2,665,777
1,000   3       2,665,777
5,000   3       2,665,777
10,000  3       2,665,777
1,000,000       1       2,420,613
---------------------------------

```
